development:
  adapter: mysql2
  encoding: utf8
  database: rbw_development
  pool: 5
  host: localhost
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: rbw_test
  pool: 5
  host: localhost
  username: root
  password: root

staging:
  adapter: mysql2
  encoding: utf8
  database: rbw_staging
  pool: 5
  host: localhost
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: rbw_production
  host: localhost
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
